"$schema" = 'https://starship.rs/config-schema.json'

# Formats
format = """
$directory\
$git_branch\
$git_status\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$python\
\n\
$docker_context\
$character\
"""


continuation_prompt = """
[](pink)\
"""
# Disable the blank line at the start of the prompt
# add_newline = false

palette = "mocha"

[palettes.latte] 
rosewater = "#DC8A78"
flamingo = "#DD7878"
pink = "#EA76CB"
mauve = "#8839EF"
red = "#D20F39"
maroon = "#E64553"
peach = "#FE640B"
yellow = "#DF8E1D"
green = "#40A02B"
teal = "#179299"
sky = "#04A5E5"
sapphire = "#209FB5"
blue = "#1E66F5"
lavender = "#7287FD"
text = "#4C4F69"
subtext1 = "#5C5F77"
subtext0 = "#6C6F85"
overlay2 = "#7C7F93"
overlay1 = "#8c8fa1"
overlay0 = "#9CA0B0"
surface2 = "#ACB0BE"
surface1 = "#BCC0CC"
surface0 = "#CCD0DA"
base = "#EFF1F5"
mantle = "#E6E9EF"
crust = "#DCE0E8"

[palettes.frappe]
rosewater = "#F2D5CF"
flamingo = "#EEBEBE"
pink = "#F4B8E4"
mauve = "#CA9EE6"
red = "#E78284"
maroon = "#EA999C"
peach = "#EF9F76"
yellow = "#E5C890"
green = "#A6D189"
teal = "#81c8be"
sky = "#99D1DB"
sapphire = "#85C1DC"
blue = "#8CAAEE"
lavender = "#BABBF1"
text = "#C6D0F5"
subtext1 = "#B5BFE2"
subtext0 = "#A5ADCE"
overlay2 = "#949CBB"
overlay1 = "#838BA7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576D"
surface0 = "#414559"
base = "#303446"
mantle = "#292C3C"
crust = "#232634"

[palettes.macchiato]
rosewater = "#F4DBD6"
flamingo = "#F0C6C6"
pink = "#F5BDE6"
mauve = "#C6A0F6"
red = "#ED8796"
maroon = "#EE99A0"
peach = "#F5A97F"
yellow = "#EED49F"
green = "#A6DA95"
teal = "#8BD5CA"
sky = "#91D7E3"
sapphire = "#7DC4E4"
blue = "#8AADF4"
lavender = "#B7BDF8"
text = "#CAD3F5"
subtext1 = "#B8C0E0"
subtext0 = "#A5ADCB"
overlay2 = "#939AB7"
overlay1 = "#8087A2"
overlay0 = "#6E738D"
surface2 = "#5B6078"
surface1 = "#494D64"
surface0 = "#363A4F"
base = "#24273A"
mantle = "#1E2030"
crust = "#181926"

[palettes.mocha]
rosewater = "#F7E0DC"
flamingo = "#F3CDCD"
pink = "#F5C2E7"
mauve = "#CBA6F7"
red = "#F38BA8"
maroon = "#EBA0AC"
peach = "#FAB387"
yellow = "#F9E2AF"
green = "#A6E3A1"
teal = "#94E2D5"
sky = "#89DCEB"
sapphire = "#74C7EC"
blue = "#89B4FA"
lavender = "#B4BEFE"
text= "#CDD6F4"
subtext1 = "#BAC2DE"
subtext0 = "#A6ADC8"
overlay2 = "#9399B2"
overlay1 = "#7F849C"
overlay0 = "#6C7086"
surface2 = "#585B70"
surface1 = "#45475A"
surface0 = "#313244"
base = "#1E1E2E"
mantle = "#181825"
crust = "#11111b"

# you can also replace your username with a neat symbol like  to save some space
[username]
show_always = false
style_user = "fg:text"
style_root = "fg:text"
format = "[$user ]($style)"

[directory]
style = "fg:lavender"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "…/"

# here is how you can shorten some long paths by text replacement
# similar to mapped_locations in oh my posh:
[directory.substitutions]
"documents" = " "
"downloads" = " "
"music" = " "
"pictures" = " "
# keep in mind that the order matters. for example:
# "important documents" = "  "
# will not be replaced, because "documents" was already substituted before.
# so either put "important documents" before "documents" or use the substituted version:
# "important  " = "  "

# languages/git
[git_branch]
symbol = ""
style = "fg:sky"
format = "[ on](fg:rosewater)[ $symbol $branch]($style)"

[git_status]
format = "[$all_status](green)[$ahead_behind](red)"

[c]
symbol = ""
style = "fg:sky"
format = "[ using](fg:rosewater)[ $symbol ($version)]($style)"

[docker_context]
symbol = ""
style = "fg:blue"
format = "[ using](fg:rosewater)[ $symbol $context]($style) $path"

[elixir]
symbol = ""
style = "fg:mauve"
format = "[ using](fg:rosewater)[ $symbol ($version) ]($style)"

[elm]
symbol = ""
style = "fg:mauve"
format = "[ using](fg:rosewater)[ $symbol ($version) ]($style)"

[golang]
symbol = ""
style = "fg:sapphire"
format = "[ using](fg:rosewater)[ $symbol ($version)]($style)"

[haskell]
symbol = ""
style = "fg:rosewater"
format = "[ using](fg:rosewater)[ $symbol ($version)]($style)"

[java]
symbol = ""
style = "fg:maroon"
format = "[ using](fg:rosewater)[ $symbol ($version)]($style)"

[julia]
symbol = ""
style = "fg:yellow"
format = "[ using](fg:rosewater)[ $symbol ($version)]($style)"

[nodejs]
symbol = ""
style = "fg:teal"
format = "[ using](fg:rosewater)[ $symbol ($version)]($style)"

[nim]
symbol = ""
style = "fg:peach"
format = "[ using](fg:rosewater)[ $symbol ($version)]($style)"

[python]
symbol = "🐍"
pyenv_version_name = true
style = "fg:teal"
format = "[ using](fg:rosewater)[ $symbol ($virtualenv:$version)]($style)"

[rust]
symbol = ""
style = "fg:red"
format = "[ using](fg:rosewater)[ $symbol ($version)]($style)"

[scala]
symbol = ""
style = "fg:maroon"
format = "[ using](fg:rosewater)[ $symbol ($version)]($style)"

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "fg:Maroon"
format = "[♥:$time]($style)"

[character]
disabled = false
success_symbol = "[](green)"
error_symbol = "[](red)"
vimcmd_symbol = "[](yellow)"
